### ISSUE TITLE
Доработка функционала

### ISSUE THREAD

**Issue by KolyaGrigoruk** [DmitryApanasik/crowdaming#2]
Сейчас многие стартапы имеют свои сайты визитки, было бы круто, если бы ты добавил при создании проекта поле для сайта. Также стоит отметить, что сейчас многие многие информационные ресурсы добавляют в свои статьи, блоги, посты видео, фото и аудиоконтент. Твои пользователи смогут добавить в описание проекта это?

**Comment by DmitryApanasik** [comment]
Насчет добавления ссылки на сайт: идея крутая, я пожалуй добавлю данную функцию. Что касается второго вопроса, то пользователи смогут загружать только фотографии к проекту.
